### ISSUE TITLE
Billing Stock System 

### ISSUE THREAD

**Issue by Pankaj-Str** [Pankaj-Str/Complete-Python-Mastery#3]
```python

--- input Section ---
Enter SKU ( Unique Number ) : 101
Enter Product Name : Books
Enter Product QT : 20
Enter Single Book Price : 120/-

Do you Want Add more [Y/N]
Y
Enter SKU ( Unique Number ) : 102
Enter Product Name : toy
Enter Product QT : 5
Enter Single Book Price : 560/-

Do you Want Add more [Y/N]
Y
Enter SKU ( Unique Number ) : 103
Enter Product Name : Samosa
Enter Product QT : 250
Enter Single Book Price : 20/-

Do you Want Add more [Y/N]
N
--- Output Section---------
------  Search Item ------
Enter Product Item Form SKU No. 103
Total Cost : 5000/-
Product Name : Samosa
QT : 250 
Single Price : 20/-



```

**Comment by developology** [comment]
https://github.com/developology/Billing-Stock-System.git

**Comment by amrita-prog** [comment]
https://github.com/amrita-prog/Billing-Stock-System

**Comment by Aashishdev01** [comment]
dict=[]

product={}
while True:

  a=input("enter the sku number:")
  b=input("eneter product name:")
  c=int(input("eneter product quantity:"))
  d=int(input("eneter product price:"))
  product={"SKU NUMBER":a,"productname":b,"quantity":c,"price":d}
  dict.append(product)
  print(dict)
  e=input("want to add more:")
  if e=="n" or e=="N":
   break
  else:
    continue
print("want to search using sku values")
f=input("enetr the sku number:")
if product["SKU NUMBER"]==f:
  for i in product:
      totalcost=product["quantity"]*product["price"]
      productname=product["productname"]
      quantity=product["quantity"]
      price=product["price"]
  print("=====bill=====")
  print("total cost=",totalcost)
  print("product name=",productname)
  print("quantity=",quantity)
  print("price=",price)
    
else:
      print("not found")

**Comment by Aashishdev01** [comment]
https://github.com/Aashishdev01/python/blob/main/billing%20stock%20system

**Comment by TheAdityaKashyap** [comment]
```python



data = {}  

while True:
    sku = int(input("Enter SKU (Unique Number): "))
    product_name = input("Enter Product Name: ")
    product_qty = int(input("Enter Product QT: "))
    product_price = int(input("Enter Single Product Price: "))

    data[sku] = {
        "name": product_name,
        "qty": product_qty,
        "price": product_price
    }

    more = input("Do you Want Add more [Y/N]: ").strip().lower()
    if more != 'y':
        break

print("\n--- Output Section ---------")
print("------  Search Item ------")

search_sku = int(input("Enter Product Item Form SKU No.: "))

if search_sku in data:
    item = data[search_sku]
    total_cost = item["qty"] * item["price"]
    print(f"Total Cost : {total_cost}/-")
    print(f"Product Name : {item['name']}")
    print(f"QT : {item['qty']}")
    print(f"Single Price : {item['price']}/-")
else:
    print("Item not found!")


```
